# Generated by Django 4.0.3 on 2022-03-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='co2',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='day',
            name='energy',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='day',
            name='trash',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='day',
            name='water',
            field=models.CharField(max_length=1000000),
        ),
    ]
