# Generated by Django 4.0.3 on 2022-03-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_day_co2_alter_day_energy_alter_day_trash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='co2',
            field=models.FloatField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='day',
            name='energy',
            field=models.FloatField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='day',
            name='trash',
            field=models.FloatField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='day',
            name='water',
            field=models.FloatField(max_length=1000000),
        ),
    ]
